services:
  go_api:
    container_name: go_app
    build: .
    ports:
      - "8080:8080"
    restart: always
    env_file: ".env"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=jitserver
      - POSTGRES_USER=ziad-eliwa
      - POSTGRES_PASSWORD=ziad1234